version: "3"

services:
  rest-api:
    build: rest-api
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/dev
    depends_on:
      - database
    networks:
      - cloud-albums-network
  database:
    build: database
    ports:
      - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: sec